### ISSUE TITLE
How to add devices to HA

### ISSUE THREAD

**Issue by GunayAnach** [malmeloo/hass-FindMy#5]
I have enabled the integration but cant seem to figure out how to add devices to the home assistant. 

<img width="841" alt="image" src="https://github.com/user-attachments/assets/80fd8fc0-a535-46bc-b906-48c5c417f56d" />

I have spun an anisette server on the same host as the home assistant and was hoping I can skip FindMy or macless-haystack and get findmy-haas to push openhaystack flashed tracker data to HA maps as trackers.  
Similar to this [FindMySync](https://github.com/MartinPham/FindMySync)?
Which works great with official and clone AirTags, but needs to run on a mac and app needs to be constantly kept on focus.

I can pull tracker data via local anisette with FindMy script and macless-haystack.

Is that possible to have tracker like integration to show them on the HA map? 

Installed by adding the repo to HA and installed via HACS. Should be latest master.

Home Assistant
Core: 2025.1.2
Frontend: 20250109.0

**Comment by malmeloo** [comment]
You've installed the integration, but not yet enabled it. In the settings you should be able to add the integration, and it will ask you whether you want to add an account or device. Add at least one account and one device, and you should be good to go.

**Comment by GunayAnach** [comment]
Ah that makes so much sense.  Thanks for making it so simple to use. I managed to add the tracker and can see it on the map. 

![image](https://github.com/user-attachments/assets/6df44772-f96a-4a89-9f0c-ad6bf1a32a9c)


I was wondering if it has an option to change its icon or picture? I can do it on the tracked devices via **known_devices.yaml** this way.

```
findmy_9CA31DBF1B7C4825BE36157603E5B276:
  name: "Elli Bag"
  mac: FINDMY_9CA31DBF-1B7C-4876-BE36-15450765B276
  icon:
  picture: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7N15nBxVuTfw36nqfZnp2bJN9j2ZLEAIazYQDAmbLJMAsqmI915RX+8VUa/KoMgiyub2ekXlurAFXF4lEUEJCSFgElmSkG32JDPJZGa6p/elqs77xyRIIJmlu6pOV/Xz/Xzu9aPTXefJTHfVU6ee8xyAEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgixDCY6AEKG66MfvcGfzSpeRWFlomPRmyRpOU2T4qNH56Jr1qxRRcdDCLEvSgBIUTr//PpaRXGcC+BUAFMYw2TOMQlApeDQzJQD+AHOWRNjvJkxtodz/rrf37dt3bp1GdHBEUKsjRIAUhSWLbvZo6rZ5YzxKwB2HsDHi46piKUBvo1z9jzn2nOvvvr0XtEBEUKshxIAItSyZdcsU1V2K2O4FEBAdDwWtQNgv5Ek/vP165/sFh0MIcQaKAEgpluxYoU7kQjdDOA2AHMEh2Mnac7xJICHN2588h3RwRBCihslAMREDdLSpXuv4pzfB2Cy6GhsjAN4FmD/vWHDE/tEB0MIKU6UABBTLFt2zTJNYz8CMFt0LCUkB7CfqKrn65s2/SImOhhCSHGhBIAY6oIL6suzWee3AH4bAEl0PCWqg3N8duPGJ/8gOhBCSPGgBIAYZunSaxZzzp4EUCs6FgIwhscYc39u/frH06JjIYSIRwkAMcTSpdfdyjn/IQCn6FjIcd7SNHbVq68+0Sw6EEKIWJQAEF0tWHCrMxCI/YJzXC86FnJSvZzjyo0bn3xFdCCEEHFk0QEQ+1iw4FKf389+D+Aq0bGQAXkZw7Xjx8/d1d6+Y5foYAghYlACQHRxwQX15bLs+SuA80THQobEwRiunDhxTmtb2w7qGUBICaIEgBSsrq7e5XI5/sgYloqOhQyLBLDLxo+fu5NmAggpPZQAkILU19fLnDueBHCJ6FhIXiTGcNmECfM2trVtbxMdDCHEPLQumxTk8GHH9zjH1aLjIAXxAPwP55+/eoroQAgh5qFVACRvS5deV885f0Z0HEQ37+RyylmbN69JiQ6EEGI8mgEgeVmy5LppnPOfiY6D6Gqew+F4RHQQhBBzUAJA8tAgAfxxAOWiIyH6YgyfXr.........
```

I changed the icon from here, but doesn't affect whats shown on the map. I thinks its the entity icon

![image](https://github.com/user-attachments/assets/e7ab9176-8bd3-441d-8e68-711d2f9c4f80)

**Comment by malmeloo** [comment]
I'm not sure about the picture, but in order to show icons on the map instead of entity names you need to set the `label_mode` attribute on the entity object for the map card config ([docs](https://www.home-assistant.io/dashboards/map/#options-for-entities))

![image](https://github.com/user-attachments/assets/075dd2d8-2256-4fdc-8a5a-96e0afe2d551)

**Comment by GunayAnach** [comment]
Awesome, known_devices.yaml seems to support it too, just need to add device name as displayed. 


```
findmy_31ca15:
  name: "iBeacon_31CA15"
  mac: FINDMY_31CA15
  icon:
  picture: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAACAASURBVHic7N15nBxVuTfw36nqfZnp2bJN9j2ZLEAIazYQDAmbLJMAsqmI915RX+8VUa/KoMgiyub2ekXlurAFXF4lEUEJCSFgElmSkG32JDPJZGa6p/elqs77xyRIIJmlu6pOV/Xz/Xzu9aPTXefJTHfVU6ee8xyAEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgixDCY6AEKG66MfvcGfzSpeRWFlomPRmyRpOU2T4qNH56Jr1qxRRcdDCLEvSgBIUTr//PpaRXGcC+BUAFMYw2TOMQlApeDQzJQD+AHOWRNjvJkxtodz/rrf37dt3bp1GdHBEUKsjRIAUhSWLbvZo6rZ5YzxKwB2HsDHi46piKUBvo1z9jzn2nOvvvr0XtEBEUKshxIAItSyZdcsU1V2K2O4FEBAdDwWtQNgv5Ek/vP165/sFh0MIcQaKAEgpluxYoU7kQjdDOA2AHMEh2Mnac7xJICHN2588h3RwRBCihslAMREDdLSpXuv4pzfB2Cy6GhsjAN4FmD/vWHDE/tEB0MIKU6UABBTLFt2zTJNYz8CMFt0LCUkB7CfqKrn65s2/SImOhhCSHGhBIAY6oIL6suzWee3AH4bAEl0PCWqg3N8duPGJ/8gOhBCSPGgBIAYZunSaxZzzp4EUCs6FgIwhscYc39u/frH06JjIYSIRwkAMcTSpdfdyjn/IQCn6FjIcd7SNHbVq68+0Sw6EEKIWJQAEF0tWHCrMxCI/YJzXC86FnJSvZzjyo0bn3xFdCCEEHFk0QEQ+1iw4FKf389+D+Aq0bGQAXkZw7Xjx8/d1d6+Y5foYAghYlACQHRxwQX15bLs+SuA80THQobEwRiunDhxTmtb2w7qGUBICaIEgBSsrq7e5XI5/sgYloqOhQyLBLDLxo+fu5NmAggpPZQAkILU19fLnDueBHCJ6FhIXiTGcNmECfM2trV
```

I managed to get an icon too

![image](https://github.com/user-attachments/assets/fe04f915-c57b-4fb7-946b-cab16497f983)

However not showing on the Map, even with the label_mode: icon . Even after a reboot. 

Maybe needs some time

![image](https://github.com/user-attachments/assets/c0a2b74e-2f99-4d54-a461-20135627c339)


Awesome integration! Thanks again
